
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017/mydatabase
      - NEXT_PUBLIC_API_ENDPOINT=localhost:3000
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
