import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import RegisterForm from '../components/RegisterForm'
import LoginForm from '../components/LoginForm'
import Manager from '../components/Manager'
import { NextPage } from 'next/types'

export interface ManagerItem{
  service: string;
  login: string;
  password: string;
}
const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  const [step, setStep] = useState<'login' | 'register' | 'manager'>('login');
  const [manager, setManager] = useState<ManagerItem[]>([]);
  const [managerKey, setManagerKey] = useState("");

  useEffect(() => {
    const manager = window.sessionStorage.getItem("manager");
    const managerKey = window.sessionStorage.getItem("managerkey");
    if (manager) {
      setManager(JSON.parse(manager));
    }
    if (managerKey){
      setManagerKey(managerKey);
      setStep("manager");
    }
  }, []); //To get manager and manager key from session storage

  return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {step === 'register' && <RegisterForm setStep={setStep} setManagerKey={setManagerKey}/>}
        {step === 'login' && <LoginForm setManager={setManager} setStep={setStep} setManagerKey={setManagerKey} />}
        {step === 'manager' && <Manager manager={manager}  managerKey={managerKey} setStep={setStep}/>}
      </main>
      </div>
  );
};

export default Home;
