import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import RegisterForm from '../components/RegisterForm'
import LoginForm from '../components/LoginForm'
import Vault from '../components/Vault'
import { NextPage } from 'next/types'

export interface VaultItem{
  service: string;
  login: string;
  password: string;
}
const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  const [step, setStep] = useState<'login' | 'register' | 'vault'>('register');
  const [vault, setVault] = useState<VaultItem[]>([]);
  const [vaultKey, setVaultKey] = useState("");

  useEffect(() => {
    const vault = window.sessionStorage.getItem("vault");
    const vaultKey = window.sessionStorage.getItem("vault key");
    if (vault) {
      setVault(JSON.parse(vault));
    }
    if (vaultKey){
      setVaultKey(vaultKey);
      setStep("vault");
    }
  }, []); //To get vault and vault key from session storage

  return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {step === 'register' && <RegisterForm setStep={setStep} setVaultKey={setVaultKey}/>}
        {step === 'login' && <LoginForm setVault={setVault} setStep={setStep} setVaultKey={setVaultKey} />}
        {step === 'vault' && <Vault vault={vault} vaultKey={vaultKey}/>}
      </main>
      </div>
  );
};

export default Home;
