import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import RegisterForm from '../components/RegisterForm'
import LoginForm from '../components/LoginForm'
import Locker from '../components/Locker'
import { NextPage } from 'next/types'

export interface LockerItem{
  service: string;
  login: string;
  password: string;
}
const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  //Set represents the current stage of the page (login, register, or locker)
  const [step, setStep] = useState<'login' | 'register' | 'locker'>('login');
  //To store and update a list of users and passwords retrieved from the db
  const [locker, setLocker] = useState<LockerItem[]>([]);
  //To storea and update the lockerKey generated 
  const [lockerKey, setLockerKey] = useState("");

  useEffect(() => {

    const lockerKey = window.sessionStorage.getItem("lockerkey");
    const locker = window.sessionStorage.getItem("locker");

    if (locker) {
      try {
        const parsedLocker = JSON.parse(locker);
        setLocker(parsedLocker);
      } catch (error) {
        console.error("Error parsing locker JSON:", error);
      }
    }
    
    //If there is a locker key present in storage then switch to the locker page
    if (lockerKey) {
      setLockerKey(lockerKey);
      setStep("locker");}},
      []); //To get locker and locker key from session storage

  return (
      <div className={`${styles.container} ${inter.className}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {step === 'register' && <RegisterForm setStep={setStep} setLockerKey={setLockerKey}/>}
        {step === 'login' && <LoginForm setLocker={setLocker} setStep={setStep} setLockerKey={setLockerKey} />}
        {step === 'locker' && <Locker locker={locker}  lockerKey={lockerKey} setStep={setStep}/>}
      </main>
      </div>
  );
};

export default Home;
